<?php
namespace SitePilotAI\Core;
use SitePilotAI\Services\Scanner;
use SitePilotAI\Services\Assistant;
use SitePilotAI\Services\ContentGenerator;
if(!defined('ABSPATH'))exit;
require_once SPAI_DIR.'app/Services/Scanner.php';require_once SPAI_DIR.'app/Services/Assistant.php';require_once SPAI_DIR.'app/Services/ContentGenerator.php';
final class Plugin{
 private static $instance;private $scanner;private $assistant;private $content_generator;
 public static function instance(){return self::$instance?:self::$instance=new self();}
 public static function defaults(){return array('business_name'=>get_bloginfo('name'),'business_type'=>'other','services'=>'','city'=>'','area'=>'','tone'=>'professional','keywords'=>'','provider'=>'none','api_key'=>'','model'=>'gpt-4.1-mini','telemetry'=>0);}
 public static function activate(){ $legacy=get_option('spai_settings',get_option('laa_settings',array()));update_option('spai_settings',wp_parse_args(is_array($legacy)?$legacy:array(),self::defaults()),false);add_option('spai_first_activation',time());add_option('spai_plan','trial');add_option('spai_activity',array());add_option('spai_scan_history',array());if(!wp_next_scheduled('spai_daily_scan'))wp_schedule_event(time()+HOUR_IN_SECONDS,'daily','spai_daily_scan');}
 public static function deactivate(){wp_clear_scheduled_hook('spai_daily_scan');}
 public function boot(){ $this->scanner=new Scanner();$this->assistant=new Assistant();$this->content_generator=new ContentGenerator();add_action('admin_menu',array($this,'menu'));add_action('admin_init',array($this,'register_settings'));add_action('admin_enqueue_scripts',array($this,'assets'));foreach(array('scan','assistant','create_content','bulk_alt','generate_meta') as $a)add_action('wp_ajax_spai_'.$a,array($this,'ajax_'.$a));add_action('spai_daily_scan',array($this,'daily_scan'));}
 private function settings(){return wp_parse_args(get_option('spai_settings',array()),self::defaults());}
 public function register_settings(){register_setting('spai_settings_group','spai_settings',array($this,'sanitize'));}
 public function sanitize($i){$c=$this->settings();return array('business_name'=>sanitize_text_field($i['business_name']??''),'business_type'=>sanitize_text_field($i['business_type']??'other'),'services'=>sanitize_textarea_field($i['services']??''),'city'=>sanitize_text_field($i['city']??''),'area'=>sanitize_text_field($i['area']??''),'tone'=>sanitize_text_field($i['tone']??'professional'),'keywords'=>sanitize_textarea_field($i['keywords']??''),'provider'=>in_array($i['provider']??'none',array('none','openai'),true)?$i['provider']:'none','api_key'=>!empty($i['api_key'])?sanitize_text_field($i['api_key']):$c['api_key'],'model'=>sanitize_text_field($i['model']??'gpt-4.1-mini'),'telemetry'=>empty($i['telemetry'])?0:1);}
 public function menu(){add_menu_page('SitePilot AI','SitePilot AI','edit_posts','sitepilot-ai',array($this,'dashboard'),'dashicons-airplane',3);add_submenu_page('sitepilot-ai','Accueil','Accueil','edit_posts','sitepilot-ai',array($this,'dashboard'));add_submenu_page('sitepilot-ai','Assistant','Assistant','edit_posts','sitepilot-ai-assistant',array($this,'assistant_page'));add_submenu_page('sitepilot-ai','Missions','Missions','edit_posts','sitepilot-ai-missions',array($this,'missions'));add_submenu_page('sitepilot-ai','Studio de contenu','Studio de contenu','edit_posts','sitepilot-ai-content',array($this,'content'));add_submenu_page('sitepilot-ai','SEO','SEO','edit_posts','sitepilot-ai-seo',array($this,'seo'));add_submenu_page('sitepilot-ai','Images','Images','upload_files','sitepilot-ai-images',array($this,'images'));add_submenu_page('sitepilot-ai','Rapports','Rapports','edit_posts','sitepilot-ai-reports',array($this,'reports'));add_submenu_page('sitepilot-ai','Réglages','Réglages','manage_options','sitepilot-ai-settings',array($this,'settings_page'));}
 public function assets($hook){if(false===strpos($hook,'sitepilot-ai'))return;wp_enqueue_style('spai',SPAI_URL.'assets/css/admin.css',array(),SPAI_VERSION);wp_enqueue_script('spai',SPAI_URL.'assets/js/admin.js',array('jquery'),SPAI_VERSION,true);wp_localize_script('spai','SPAI',array('ajax'=>admin_url('admin-ajax.php'),'nonce'=>wp_create_nonce('spai'),'admin'=>admin_url(),'strings'=>array('error'=>'Une erreur est survenue.')));}
 private function verify($cap='edit_posts'){check_ajax_referer('spai','nonce');if(!current_user_can($cap))wp_send_json_error(array('message'=>'Action non autorisée.'),403);}
 private function trial(){$start=(int)get_option('spai_first_activation',time());$days=(int)floor((time()-$start)/DAY_IN_SECONDS);return array('remaining'=>max(0,7-$days),'expired'=>$days>=7);}
 private function wrap_start($title,$sub=''){$t=$this->trial();echo '<div class="wrap spai-wrap"><header class="spai-top"><div class="spai-brand"><span>S</span><div><b>SitePilot AI</b><small>by Lorraine Digital</small></div></div><div class="spai-badge">'.($t['expired']?'Accès découverte terminé':esc_html($t['remaining'].' jour(s) de découverte')).'</div></header><div class="spai-title"><h1>'.esc_html($title).'</h1><p>'.esc_html($sub).'</p></div>';}
 private function wrap_end(){echo '</div>';}
 private function log($type,$text){$a=get_option('spai_activity',array());array_unshift($a,array('time'=>current_time('mysql'),'type'=>$type,'text'=>$text));update_option('spai_activity',array_slice($a,0,100),false);}
 public function daily_scan(){$d=$this->scanner->run();$this->log('scan','Analyse automatique terminée — score '.$d['score'].'/100');}
 public function ajax_scan(){$this->verify();$d=$this->scanner->run();$this->log('scan','Analyse manuelle terminée — score '.$d['score'].'/100');wp_send_json_success($d);}
 public function ajax_assistant(){$this->verify();$msg=sanitize_textarea_field(wp_unslash($_POST['message']??''));$answer=$this->assistant->answer($msg,$this->settings(),get_option('spai_last_scan',array()));$this->log('assistant','Conversation avec '.$answer['agent']);wp_send_json_success($answer);}
 public function ajax_create_content(){$this->verify();$r=array();foreach(array('type','subject','objective','city','tone','keywords','length') as $k)$r[$k]=sanitize_text_field(wp_unslash($_POST[$k]??''));$g=$this->content_generator->generate($r,$this->settings());if(is_wp_error($g))wp_send_json_error(array('message'=>$g->get_error_message()));$post_type='page'===$r['type']?'page':'post';$id=wp_insert_post(array('post_type'=>$post_type,'post_status'=>'draft','post_title'=>$g['title'],'post_content'=>$g['content'],'post_excerpt'=>$g['excerpt']),true);if(is_wp_error($id))wp_send_json_error(array('message'=>$id->get_error_message()));if(!empty($g['meta_description']))update_post_meta($id,'_yoast_wpseo_metadesc',$g['meta_description']);$this->log('content','Brouillon '.$r['type'].' créé : '.$g['title']);wp_send_json_success(array('id'=>$id,'url'=>get_edit_post_link($id,'raw'),'source'=>$g['source'],'title'=>$g['title']));}
 public function ajax_bulk_alt(){$this->verify('upload_files');global $wpdb;$ids=$wpdb->get_col("SELECT p.ID FROM {$wpdb->posts} p LEFT JOIN {$wpdb->postmeta} pm ON p.ID=pm.post_id AND pm.meta_key='_wp_attachment_image_alt' WHERE p.post_type='attachment' AND p.post_mime_type LIKE 'image/%' AND (pm.meta_value IS NULL OR pm.meta_value='') LIMIT 100");$done=0;foreach($ids as $id){$alt=$this->suggest_alt($id);if($alt){update_post_meta($id,'_wp_attachment_image_alt',$alt);$done++;}}$this->log('images',$done.' texte(s) ALT généré(s) automatiquement');wp_send_json_success(array('count'=>$done));}
 private function suggest_alt($id){$caption=get_post_field('post_excerpt',$id);if($caption)return sanitize_text_field($caption);$title=get_the_title($id);$title=preg_replace('/[-_]+/',' ',$title);$title=preg_replace('/\b(img|image|dsc|photo)\s*\d*\b/i','',$title);$title=trim(preg_replace('/\s+/',' ',$title));if(!$title){$parent=wp_get_post_parent_id($id);$title=$parent?get_the_title($parent):'';}return sanitize_text_field($title);}
 public function ajax_generate_meta(){$this->verify();global $wpdb;$ids=$wpdb->get_col("SELECT ID FROM {$wpdb->posts} WHERE post_status='publish' AND post_type IN ('post','page') ORDER BY ID DESC LIMIT 200");$done=0;foreach($ids as $id){if(get_post_meta($id,'_yoast_wpseo_metadesc',true)||get_post_meta($id,'rank_math_description',true))continue;$text=has_excerpt($id)?get_the_excerpt($id):wp_trim_words(wp_strip_all_tags(get_post_field('post_content',$id)),28,'…');$text=trim($text);if($text){update_post_meta($id,'_yoast_wpseo_metadesc',mb_substr($text,0,155));$done++;}}$this->log('seo',$done.' description(s) SEO générée(s)');wp_send_json_success(array('count'=>$done));}
 private function scan(){return get_option('spai_last_scan',array());}
 public function dashboard(){if(!current_user_can('edit_posts'))return;$s=$this->settings();$d=$this->scan();$u=wp_get_current_user();$n=$u->first_name?:$u->display_name;$score=$d['score']??'—';$complete=array_filter(array($s['business_name'],$s['business_type'],$s['services'],$s['city'],$s['keywords']));$profile=(int)round(count($complete)/5*100);$this->wrap_start('Bonjour '.$n.' 👋','Votre copilote présente les priorités de '.($s['business_name']?:get_bloginfo('name')).'.');?><section class="spai-hero"><div><span class="eyebrow">Brief du jour</span><h2>Une vision claire, puis des actions concrètes.</h2><p>Analysez le site, corrigez les priorités et créez vos contenus depuis un seul espace.</p></div><button class="spai-btn primary" id="spai-scan">Analyser maintenant</button></section><div id="spai-notice"></div><div class="spai-grid"><main><div class="spai-section-head"><h2>Actions rapides</h2><a href="<?php echo esc_url(admin_url('admin.php?page=sitepilot-ai-missions'));?>">Toutes les missions</a></div><div class="mission-grid"><?php foreach(array(array('Créer un contenu','Article, actualité, page ou FAQ','dashicons-edit','sitepilot-ai-content'),array('Optimiser le SEO','Descriptions et contenus','dashicons-chart-line','sitepilot-ai-seo'),array('Compléter les images','Textes ALT en un clic','dashicons-format-image','sitepilot-ai-images'),array('Parler à SitePilot','Conseils contextualisés','dashicons-format-chat','sitepilot-ai-assistant')) as $x):?><a class="mission" href="<?php echo esc_url(admin_url('admin.php?page='.$x[3]));?>"><span class="dashicons <?php echo esc_attr($x[2]);?>"></span><div><b><?php echo esc_html($x[0]);?></b><small><?php echo esc_html($x[1]);?></small></div></a><?php endforeach;?></div><section class="spai-card"><div class="spai-section-head"><h2>Recommandations prioritaires</h2><span>Temps estimé</span></div><div id="spai-recos"><?php echo $this->render_recos($d['recommendations']??array());?></div></section></main><aside><section class="spai-card score"><div class="score-ring" data-score="<?php echo esc_attr(is_numeric($score)?$score:0);?>"><strong id="spai-score"><?php echo esc_html($score);?></strong><span>/100</span></div><h3>Santé globale</h3><p><?php echo is_numeric($score)?esc_html($score>=85?'Très bonne base':($score>=70?'Quelques améliorations utiles':'Des priorités sont à traiter')):'Lancez une première analyse';?></p></section><section class="spai-card"><h3>Mémoire d’entreprise</h3><div class="progress"><i style="width:<?php echo esc_attr($profile);?>%"></i></div><p><?php echo esc_html($profile);?> % complétée</p><a href="<?php echo esc_url(admin_url('admin.php?page=sitepilot-ai-settings'));?>">Compléter le profil</a></section><section class="spai-card"><h3>Activité récente</h3><?php echo $this->activity_html(5);?></section></aside></div><?php $this->wrap_end();}
 private function render_recos($r){if(!$r)return '<div class="empty">Aucune analyse disponible.</div>';$o='';foreach(array_slice($r,0,6) as $x)$o.='<a class="reco" href="'.esc_url(admin_url($x['url'])).'"><span class="priority">'.esc_html(substr($x['priority'],0,1)).'</span><div><small>'.esc_html($x['category']).'</small><b>'.esc_html($x['title']).'</b><p>'.esc_html($x['description']).'</p></div><em>'.(int)$x['minutes'].' min</em></a>';return $o;}
 private function activity_html($limit=10){$a=array_slice(get_option('spai_activity',array()),0,$limit);if(!$a)return '<div class="empty">Aucune activité enregistrée.</div>';$o='<div class="timeline">';foreach($a as $x)$o.='<div><i></i><span>'.esc_html(mysql2date('d/m H:i',$x['time'])).'</span><p>'.esc_html($x['text']).'</p></div>';return $o.'</div>';}
 public function assistant_page(){$this->wrap_start('Assistant','Exprimez votre objectif : SitePilot choisit le bon expert.');?><section class="spai-card chat"><div id="spai-chat"><div class="bubble bot"><b>SitePilot AI</b><p>Bonjour 👋 Que souhaitez-vous améliorer aujourd’hui ?</p></div></div><div class="quick"><button>Créer une actualité</button><button>Analyser mon SEO</button><button>Mon site est-il sécurisé ?</button><button>Donne-moi une idée marketing</button></div><form id="spai-chat-form"><textarea id="spai-message" placeholder="Exemple : prépare une actualité sur nos horaires d’été…"></textarea><button class="spai-btn primary">Envoyer</button></form></section><?php $this->wrap_end();}
 public function missions(){$this->wrap_start('Missions','Choisissez un résultat, SitePilot vous conduit vers l’action.');?><div class="big-missions"><?php foreach(array(array('Développer ma visibilité','Audit SEO, contenus et images.','SEO','sitepilot-ai-seo'),array('Publier du contenu','Articles, actualités, pages et FAQ.','Contenu','sitepilot-ai-content'),array('Optimiser mes images','Compléter automatiquement les textes ALT.','Images','sitepilot-ai-images'),array('Sécuriser mon site','HTTPS, mises à jour et administrateurs.','Sécurité','sitepilot-ai')) as $x):?><article class="spai-card mission-large"><span><?php echo esc_html($x[2]);?></span><h2><?php echo esc_html($x[0]);?></h2><p><?php echo esc_html($x[1]);?></p><a class="spai-btn" href="<?php echo esc_url(admin_url('admin.php?page='.$x[3]));?>">Démarrer</a></article><?php endforeach;?></div><?php $this->wrap_end();}
 public function content(){$s=$this->settings();$this->wrap_start('Studio de contenu','Générez un brouillon WordPress structuré et prêt à relire.');?><section class="spai-card"><form id="spai-content-form" class="form-grid"><label>Format<select id="spai-type"><option value="news">Actualité</option><option value="article">Article de blog</option><option value="page">Page de service</option><option value="faq">FAQ</option></select></label><label>Sujet<input id="spai-subject" required placeholder="Ex. Nos nouveaux services IA"></label><label>Objectif<input id="spai-objective" value="Informer et inciter à nous contacter"></label><label>Ville ciblée<input id="spai-city" value="<?php echo esc_attr($s['city']);?>"></label><label>Ton<select id="spai-tone"><option>professionnel</option><option>chaleureux</option><option>direct</option><option>expert</option></select></label><label>Longueur<select id="spai-length"><option value="short">Courte</option><option value="medium" selected>Moyenne</option><option value="long">Longue</option></select></label><label class="wide">Mots-clés<input id="spai-keywords" value="<?php echo esc_attr($s['keywords']);?>" placeholder="Séparez par des virgules"></label><div class="form-action"><button class="spai-btn primary">Créer le brouillon</button></div></form><div id="spai-content-result"></div><p class="note">Mode local : trame éditoriale structurée. Avec OpenAI : rédaction complète contextualisée et méta-description.</p></section><?php $this->wrap_end();}
 public function seo(){$d=$this->scan();$this->wrap_start('Visibilité & SEO','Analyse, priorités et premières corrections assistées.');?><div class="metric-grid"><?php foreach(array('Score SEO'=>($d['scores']['seo']??'—').'/100','Descriptions manquantes'=>$d['no_meta']??'—','Contenus courts'=>$d['thin']??'—','Images sans ALT'=>$d['missing_alt']??'—') as $k=>$v):?><section class="spai-card metric"><span><?php echo esc_html($k);?></span><strong><?php echo esc_html($v);?></strong></section><?php endforeach;?></div><section class="spai-card action-panel"><div><h2>Descriptions SEO automatiques</h2><p>SitePilot utilise l’extrait ou le début du contenu et enregistre une description compatible Yoast SEO.</p></div><button id="spai-generate-meta" class="spai-btn primary">Générer les descriptions manquantes</button></section><div id="spai-seo-result"></div><section class="spai-card"><h2>Plan d’action SEO</h2><?php echo $this->render_recos(array_values(array_filter($d['recommendations']??array(),function($r){return in_array($r['category'],array('SEO','Images','Contenu'),true);})));?></section><?php $this->wrap_end();}
 public function images(){$d=$this->scan();$this->wrap_start('Images','Complétez les textes ALT manquants de façon contrôlée.');?><div class="metric-grid"><section class="spai-card metric"><span>Images analysées</span><strong><?php echo esc_html($d['images']??'—');?></strong></section><section class="spai-card metric"><span>Sans texte ALT</span><strong><?php echo esc_html($d['missing_alt']??'—');?></strong></section><section class="spai-card metric"><span>Score images</span><strong><?php echo esc_html(isset($d['scores']['images'])?$d['scores']['images'].'/100':'—');?></strong></section></div><section class="spai-card action-panel"><div><h2>Correction automatique</h2><p>Le texte ALT est proposé depuis la légende, le titre du média ou la page parente. Les 100 premières images manquantes sont traitées.</p></div><button id="spai-bulk-alt" class="spai-btn primary">Compléter les ALT manquants</button></section><div id="spai-image-result"></div><section class="spai-card"><a class="spai-btn" href="<?php echo esc_url(admin_url('upload.php?mode=list'));?>">Vérifier dans la médiathèque</a></section><?php $this->wrap_end();}
 public function reports(){$d=$this->scan();$h=array_slice(get_option('spai_scan_history',array()),0,12);$this->wrap_start('Rapports','Historique local des analyses et actions.');?><div class="report-grid"><section class="spai-card"><h2>Dernière analyse</h2><p><?php echo !empty($d['scanned_at'])?esc_html(mysql2date('d/m/Y à H:i',$d['scanned_at'])):'Aucune analyse';?></p><div class="report-score"><?php echo esc_html($d['score']??'—');?>/100</div></section><section class="spai-card"><h2>Évolution du score</h2><?php if(!$h):?><div class="empty">Lancez plusieurs analyses pour voir l’évolution.</div><?php else:?><div class="score-bars"><?php foreach(array_reverse($h) as $x):?><div title="<?php echo esc_attr(mysql2date('d/m H:i',$x['scanned_at']).' — '.$x['score'].'/100');?>"><i style="height:<?php echo esc_attr((int)$x['score']);?>%"></i></div><?php endforeach;?></div><?php endif;?></section></div><section class="spai-card"><h2>Journal d’activité</h2><?php echo $this->activity_html(30);?></section><?php $this->wrap_end();}
 public function settings_page(){if(!current_user_can('manage_options'))return;$s=$this->settings();$this->wrap_start('Réglages','Configurez la mémoire d’entreprise et la connexion IA.');?><form method="post" action="options.php" class="settings-form"><?php settings_fields('spai_settings_group');?><section class="spai-card"><h2>Mémoire d’entreprise</h2><div class="form-grid"><label>Nom<input name="spai_settings[business_name]" value="<?php echo esc_attr($s['business_name']);?>"></label><label>Activité<input name="spai_settings[business_type]" value="<?php echo esc_attr($s['business_type']);?>" placeholder="Ex. agence web et IA"></label><label>Ville<input name="spai_settings[city]" value="<?php echo esc_attr($s['city']);?>"></label><label>Zone d’intervention<input name="spai_settings[area]" value="<?php echo esc_attr($s['area']);?>"></label><label class="wide">Services<textarea name="spai_settings[services]" rows="4"><?php echo esc_textarea($s['services']);?></textarea></label><label class="wide">Mots-clés prioritaires<textarea name="spai_settings[keywords]" rows="3"><?php echo esc_textarea($s['keywords']);?></textarea></label><label>Ton<select name="spai_settings[tone]"><?php foreach(array('professional'=>'Professionnel','friendly'=>'Chaleureux','expert'=>'Expert','direct'=>'Direct') as $v=>$l)echo '<option value="'.esc_attr($v).'" '.selected($s['tone'],$v,false).'>'.esc_html($l).'</option>';?></select></label></div></section><section class="spai-card"><h2>Connexion IA</h2><div class="form-grid"><label>Fournisseur<select name="spai_settings[provider]"><option value="none" <?php selected($s['provider'],'none');?>>Mode local</option><option value="openai" <?php selected($s['provider'],'openai');?>>OpenAI</option></select></label><label>Modèle<input name="spai_settings[model]" value="<?php echo esc_attr($s['model']);?>"></label><label class="wide">Clé API<input type="password" name="spai_settings[api_key]" value="" placeholder="Laissez vide pour conserver la clé"><small>Utilisez une clé dédiée avec une limite de dépenses.</small></label></div></section><?php submit_button('Enregistrer les réglages','primary spai-save');?></form><?php $this->wrap_end();}
}
